-- Table: public.votacion

-- DROP TABLE public.votacion;

CREATE TABLE public.votacion
(
    alias character varying COLLATE pg_catalog."default",
    candidato character varying COLLATE pg_catalog."default",
    comuna character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    idvotacion integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying COLLATE pg_catalog."default",
    region character varying COLLATE pg_catalog."default",
    rut character varying COLLATE pg_catalog."default",
    medio character varying COLLATE pg_catalog."default",
    CONSTRAINT idvotacion PRIMARY KEY (idvotacion)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.votacion
    OWNER to postgres;